#The language you want the plugin to run in. Current options: 'lang_en' - English
language: 'lang_en'

#Should we log trades in 'logs.yml' ?
#Default: true
logTrades: true
#Should we log when a user was banned and who banned them (from trading) in 'logs.yml' ?
#Default: true
logBans: true

#The amount of time (in seconds) a trade request will last before it expires.
#Default: 30
requestDuration: 30

#The amount of time (in seconds) to wait before completing the trade AFTER both players have clicked 'ready'.
#Default: 3
completeTimer: 3

#Should we allow an option to trade money (currency)?
#If this is false, the currency button will be hidden.
#We currently hook into Vault, which supports (most) economy plugins.
#Vault MUST BE installed for this option.
#Default: true
tradeInGameMoney: true

#Should only allow players to trade with players within a certain radius of them?
#Default: true
tradeRadiusToggle: true
#If enabled, what should the radius be? (e.g. 40 is a 40 block radius).
#Note, the Y radius is not affected. E.g. radius is 40, but the players are at Y = 100 and Y = 0,
#as long as their X and Z values are withing each other, they can still trade.
#Default 100
tradeRadiusAmount: 100

#Items in this list will be blocked from trades. Note, COMMAND is just the name for COMMAND_BLOCK in older versions. :)
#Only material names will work.
blacklistItems:
  - BARRIER
  - LIGHT
  - DEBUG_STICK
  - COMMAND_BLOCK
  - COMMAND
  - COMMAND_CHAIN
  - COMMAND_REPEATING

#Should we notify you when a new update is available for this plugin?
#We STRONGLY recommend enabling this as we push out updates with new features and bug fixes you don't want to miss.
#Default: true
updateChecker: true

#DO NOT CHANGE THIS! IT WILL BREAK THIS PLUGIN!
fileVersion: 0